<script src="{{ asset('assets/js/jquery.min.js') }}"></script>
<script src="{{ asset('assets/js/popper.min.js') }}"></script>
<script src="{{ asset('assets/js/moment.min.js') }}"></script>
<script src="{{ asset('assets/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/js/simplebar.min.js') }}"></script>
<script src="{{ asset('assets/js/daterangepicker.js') }}"></script>
<script src="{{ asset('assets/js/jquery.stickOnScroll.js') }}"></script>
<script src="{{ asset('assets/js/tinycolor-min.js') }}"></script>
<script src="{{ asset('assets/js/config.js') }}"></script>
<script src="{{ asset('assets/js/d3.min.js') }}"></script>
<script src="{{ asset('assets/js/topojson.min.js') }}"></script>
<script src="{{ asset('assets/js/datamaps.all.min.js') }}"></script>
<script src="{{ asset('assets/js/datamaps-zoomto.js') }}"></script>
<script src="{{ asset('assets/js/datamaps.custom.js') }}"></script>
<script src="{{ asset('assets/js/Chart.min.js') }}"></script>

<script src="{{ asset('assets/js/gauge.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('assets/js/apexcharts.min.js') }}"></script>
<script src="{{ asset('assets/js/apexcharts.custom.js') }}"></script>
<script src="{{ asset('assets/js/jquery.mask.min.js') }}"></script>
<script src="{{ asset('assets/js/select2.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.steps.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.validate.min.js') }}"></script>
<script src="{{ asset('assets/js/jquery.timepicker.js') }}"></script>
<script src="{{ asset('assets/js/dropzone.min.js') }}"></script>
<script src="{{ asset('assets/js/uppy.min.js') }}"></script>
<script src="{{ asset('assets/js/quill.min.js') }}"></script>
<script src="{{ asset('assets/js/apps.js') }}"></script>
<!-- <script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/js/dataTables.bootstrap4.min.js') }}"></script> -->
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{{ asset('assets/DataTable-1.12.1/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/DataTable-1.12.1/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/DataTable-1.12.1/js/jszip.min.js') }}"></script>
<script src="{{ asset('assets/DataTable-1.12.1/js/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/DataTable-1.12.1/js/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/DataTable-1.12.1/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/DataTable-1.12.1/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/DataTable-1.12.1/js/buttons.colVis.min.js') }}"></script>
<script src="{{ asset('assets/Datepicker/kendo.all.min.js') }}"></script>